# Generated by Django 4.2 on 2024-07-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_otp_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='comment',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
