# Generated by Django 4.2 on 2024-07-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_file_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_download_date',
            field=models.DateTimeField(null=True),
        ),
    ]
