# Generated by Django 4.2 on 2024-07-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_file_last_download_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_download_date',
            field=models.DateTimeField(null=True),
        ),
    ]
